language: node_js
node_js:
  - "6"
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - g++-4.8-multilib
      - libgtk2.0-0
      - libx11-dev
script:
  - npm test
